#!/usr/bin/env bash
# This script is displaying displays numbers from 1 to 100.
for ((counter=1;counter<=100;counter++));do
	if [ $((counter%3)) -eq 0 ] && [ $((counter%5)) -eq 0 ];then
		echo "FizzBuzz"
	elif [ $((counter%3)) -eq 0 ];then
		echo "Fizz"
	elif [ $((counter%5)) -eq 0 ];then
		echo "Buzz"
	else
		echo "$counter"
	fi
done
