#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
counter=1
while [ $counter -le 11 ];do
	if [ $counter -eq 10 ];then
		echo "Hi"
	else
		echo "Best School"
	fi
	((counter++))
done
